### ISSUE TITLE
Logging In

### ISSUE THREAD

**Issue by Memesaremydreams** [Lavoaster/IP.Board-Steam-Authentication-Method#82]
Since the latest update of Invision Power 4.1.19 or whatever it is, other people sometimes get signed in as other people.

**Comment by madman32395** [comment]
Hmm. That doesn't sound very good. Message me on steam and I'll take a look
via ACP .

On Mar 17, 2017 16:28, "Memesaremydreams" <notifications@github.com> wrote:

Since the latest update of Invision Power 4.1.19 or whatever it is, other
people sometimes get signed in as other people.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lavoaster/IP.Board-Steam-Authentication-Method/issues/82>,
or mute the thread
