### ISSUE TITLE
Template/core/global/plugins/steam does not exist

### ISSUE THREAD

**Issue by thecarnivore** [Lavoaster/IP.Board-Steam-Authentication-Method#85]
Hi, trying to install your plugin on our page and this is what we're seeing.  Any suggestions on how to fix it?

![image](https://user-images.githubusercontent.com/29940287/27916748-a2c8dca6-622f-11e7-9784-bedc732dcd8a.png)

**Comment by madman32395** [comment]
Have you uploaded the files in the upload folder correctly or at all? Ips
version? PHP version, and is curl enabled?

**Comment by thecarnivore** [comment]
The files have been uploaded by Invision Customer Support after we uploaded
them and couldn't figure out where to put the Steam API (login method is
gone).  It's an IPS hosted forum site running the latest 4.1 or 4.2,
whichever.  Curl is enabled.  not sure what version of PHP they are running.

**Comment by madman32395** [comment]
Ah. Okay, usually they are pretty good at getting you online (file-wise) .
CiC is able to run the steam login.

Have you tried using a default (unmodified/stock) theme? I have seen before
if everything is installed correctly, but the theme will gunk it up.

If not let me know and I can look deeper into this on your installation.

**Comment by thecarnivore** [comment]
If you could look into it that would be great.  Paid $40 for the theme and
would really like to get it working.  Taman did the theme and said it's not
an issue with the theme itself.

**Comment by madman32395** [comment]
What site is this for? And have we tried the default/stock theme?

**Comment by thecarnivore** [comment]
http://www.tacticalcarnage.org

No, I have not tried the stock theme yet.  Trying that now.

**Comment by thecarnivore** [comment]
Default Theme still has the same problem.

[image: Inline image 1]

**Comment by madman32395** [comment]
hmm. hit me up on steam (madman32395) or discord (madman32395#1736) ; cool if i take a look?

**Comment by madman32395** [comment]
Appeared that IPS installed the upload files correctly, there was a steam_login placeholder in the login handlers, went to plugins and noticed it was not installed, downloaded the plugin from github and installed the xml. Entered api key provided by Carnivore, validated steam login works for both front and backend and that it imports display picture. Steam also displays and operates on custom theme.  Glad to help ya out :D
___________________________________
Future note for Community In the Cloud (CiC) users; submit ticket with IPS to have them upload the files in the upload directory (they are aware on how to do this; they do this because you don't have FTP access), once they uploaded, download and extract the .xml , goto your ACP and goto System>Site Features> Plugins> click 'Install New Plugin'> upload extracted .xml  ; once this is done goto System>Settings>Login Handlers> find steam and click edit on the right side. Enter Steam API Key by following the link under the box asked for the key. after that, it should be fully installed and ready to play 🏆

**Comment by thecarnivore** [comment]
Excellent job and very friendly.  I'll be looking for more of your guys' widgets, integrations, and apps.
